databases:
  - name: csldb
    plan: free
    databaseName: csl
    user: csl

services:
  - type: web
    plan: free
    name: csl
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn csl.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: csldb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
      - key: CLOUDINARY_URL
        value: "cloudinary://213289612852938:W3vLc8IsC3PWf77tF6L6TAUCkoI@ddwvkwson"
      - key: CLOUDINARY_CLOUD_NAME
        value: "ddwvkwson"
      - key: CLOUDINARY_API_KEY
        value: "213289612852938"
      - key: CLOUDINARY_API_SECRET
        value: "W3vLc8IsC3PWf77tF6L6TAUCkoI"