<<<<<<< HEAD
services:
  - type: web
    plan: free
    name: csl
=======
databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
>>>>>>> f59b16b (Aggiunta configurazione per deploy su render)
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn csl.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
<<<<<<< HEAD
          name: csldb
=======
          name: mysitedb
>>>>>>> f59b16b (Aggiunta configurazione per deploy su render)
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
<<<<<<< HEAD
        value: False
      - key: CLOUDINARY_URL
        value: "cloudinary://213289612852938:W3vLc8IsC3PWf77tF6L6TAUCkoI@ddwvkwson"
      - key: CLOUDINARY_CLOUD_NAME
        value: "ddwvkwson"
      - key: CLOUDINARY_API_KEY
        value: "213289612852938"
      - key: CLOUDINARY_API_SECRET
        value: "W3vLc8IsC3PWf77tF6L6TAUCkoI"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "alessandro"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "Arciv123!"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "alessandro.matteucci@hotmail.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "csl.settings"
=======
        value: True
>>>>>>> f59b16b (Aggiunta configurazione per deploy su render)
