# Generated by Django 5.2 on 2025-04-17 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_marketing_alter_carousel_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketing",
            name="order",
            field=models.IntegerField(
                default=0,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
    ]
