# Generated by Django 5.2 on 2025-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
